[build]
  command = """
    if [ -d \"flutter\" ]; then cd flutter && git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && \\
    flutter/bin/flutter config --enable-web && \\
    flutter/bin/flutter build web --release
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200